### ISSUE TITLE
I try to register I get an error

### ISSUE THREAD

**Issue by htdocz** [abdelfetah18/watch-together#1]
![image](https://github.com/abdelfetah18/watch-together/assets/84078276/ab3883ad-bb81-42c7-9ccf-df47e5d59d6b)
"npm install, npm build, npm run dev" I did and ran these but when I try to register I get an error

**Comment by abdelfetah18** [comment]
You need to setup the database, i am using sanity io so you need to create an account in [SanityIO](https://www.sanity.io/) website and create a database by following there documentation, and i will add the schema of the database then you can use that schema. also dont forget to change the credentials in the database file.

**Comment by htdocz** [comment]
I really like your project. Thanks

**Comment by abdelfetah18** [comment]
No Problem, here is the schem:
https://github.com/abdelfetah18/watch-together/tree/main/database_schema
